#!/bin/bash


#3 Сколько строк выведет команда: head 1 2 <3 | tail -15

head 1 2 <3 | tail -15

#head 1 2 <3 = takes the 10 lines of the files '1' and '2'
#tail -15 = takes de last 15 lines of the previous command output
#head 1 2 <3

#----------------------------------------------------------------------------------------

#The output of the first part head 1 2 <3 is, it takes into account only the file 1 and 2 and ignores the file number 3:
#==> 1 <==
#File 1
#1
#2
#3
#4
#5
#6
#7
#8
#9

#==> 2 <==
#File 2
#21
#22
#23
#24
#25
#26
#27
#28
#29
#----------------------------------------------------------------------------------------------


#The whole command output is, because after the first part, we take the last 15 lines of the previous output (tail -15):
#7
#8
#9

#==> 2 <==
#File 2
#21
#22
#23
#24
#25
#26
#27
#28
#29
